# Generated by Django 2.1.4 on 2019-06-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_url', models.CharField(default='', help_text='location', max_length=80, verbose_name='location')),
                ('title', models.CharField(default='', help_text='title', max_length=80, verbose_name='title')),
                ('userid', models.IntegerField(default=0, help_text='userid', verbose_name='userid')),
                ('created_date', models.DateTimeField(help_text='date time', verbose_name='data tiem')),
                ('states', models.IntegerField(choices=[(1, 'expire'), (2, 'active'), (0, 'disable')], help_text='status', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Topics',
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
